name: Update News and Posts

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-news-and-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Update Posts Data
        run: |
          python dashboard.py

      - name: Commit and push changes for NewPosts.json
        run: |
          git config --local user.email "threatwatch.protect@gmail.com"
          git config --local user.name "Threatwatch"
          git add NewPosts.json
          git diff --cached --exit-code || git commit -m "Auto-update JSON data for posts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
