name: Update News and Posts

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-news-and-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Update Posts Data
        run: |
          python dashboard.py

      - name: Commit changes (if any)
        run: |
          git config user.email "threatwatch.protect@gmail.com"
          git config user.name "Threatwatch"
          git add NewPosts.json
          git diff --cached --quiet || git commit -m "Auto-update JSON data for posts"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
