name: Update News and Posts

on:
  schedule:
    - cron: '50 * * * *'  # Runs at the 50th minute of every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-news-and-posts:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install system dependencies (to fix g++ errors)
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev libffi-dev libssl-dev g++

    # Step 3: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: 'pip'  # Enables caching for dependencies

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install thinc --no-build-isolation  # Avoids build issues
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm  # Install spaCy model

    # # Step 5: Run script to update news.json
    # - name: Update News Data
    #   run: |
    #     python dashboard2.py  # Run the script for news.json

    # Step 6: Run script to update posts.json
    - name: Update Posts Data
      run: |
        python dashboard.py  # Run the script for NewPosts.json

    # # Step 7: Commit and push changes for news.json
    # - name: Commit and push changes for news.json
    #   run: |
    #     git config --local user.email "faisal.s.albargan@gmail.com"
    #     git config --local user.name "FSBARGAN"
    #     git add news.json
    #     git diff --cached --exit-code || git commit -m "Auto-update JSON data for news"
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 8: Commit and push changes for posts.json
    - name: Commit and push changes for NewPosts.json
      run: |
        git config --local user.email "faisal.s.albargan@gmail.com"
        git config --local user.name "FSBARGAN"
        git add NewPosts.json
        git diff --cached --exit-code || git commit -m "Auto-update JSON data for posts"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
