name: Update JSON

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm  # Install spaCy model

    - name: Run script
      run: |
        python dashboard.py  # Replace with your actual script name

    - name: Push changes
      run: |
        git config --local user.email "faisal.s.albargan@gmail.com"
        git config --local user.name "FSBARGAN"
        git add new_messages.json
        git commit -m "Auto-update JSON data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
