name: Update News and Posts

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-news-and-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Update Posts Data
        timeout-minutes: 10
        env:
          PYTHONUNBUFFERED: "1"
        run: python -u dashboard.py

      - name: Commit changes (if any)
        run: |
          git config --local user.email "threatwatch.protect@gmail.com"
          git config --local user.name "Threatwatch"
          git add NewPosts.json
          git diff --cached --quiet || git commit -m "Auto-update JSON data for posts"

      - name: Push changes
        run: |
          git pull --rebase origin "${{ github.ref_name }}"
          git push origin HEAD:${{ github.ref_name }}
