name: Update News and Posts

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-news-and-posts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      # Step 4: Run your script
      - name: Update Posts Data
        run: python dashboard.py

      # Step 5: Commit and push changes for NewPosts.json
      - name: Commit and push changes for NewPosts.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "threatwatch.protect@gmail.com"
          git config --local user.name "Threatwatch"
          git add NewPosts.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto-update JSON data for posts"
          git push origin HEAD:${{ github.ref_name }}
